"""The manual part: what to redact and what to call the result, per CV.

Everything else in this tool is automatic. A surname cannot be, because a
surname is just a word -- nothing in "Sharma" says it is a name rather than a
place or a product. So each CV gets one line here, added after reading its
header (`python -m resume_scrubber.scan` prints them).

Four tables, keyed by the *source* filename:

    SURNAMES  every family name and identifier to remove. List all of them:
              middle names ("Mithilesh Chandrabhan Patil" needs both) and any
              variant that only appears inside a handle -- one candidate's
              LinkedIn is `prity-rawat`, so "Rawat" is listed as well. A token
              beginning `re:` is spliced in as a raw regex, for a bare initial
              that must only match in one place.
    OUT_NAME  the output filename, because the source filename usually leaks
              the surname too.
    REINSERT  a first name to draw back in, where first and last are a single
              glued token ("RafiAhmed") so the whole word has to go.
    PHOTOS    image xrefs to delete. Only faces: logos and icons stay.

A CV missing from SURNAMES is still processed -- the pattern rules run on
everything -- but its surname will survive, and the run warns about it.
"""

# Per-file surname / extra-identifier tokens to redact (case-insensitive, whole word).
SURNAMES: dict[str, list[str]] = {
    "Aakash_PythonDeveloper (1).pdf": ["Aggarwal"],
    "Aman_Chaudhary_Resume.pdf": ["Chaudhary"],
    "Aman_Resume.docx": [],
    "Amar (1).pdf": ["Kumar", "verma"],
    "Amit_Kumar_Resume_PDF_Format-1 (1).pdf": ["Kumar", "Prajapati", "Kalera"],
    "Amol Kale.pdf": ["Kale"],  # scanned, handled via OCR
    # 0310: orphaned tail of the phone number, sits in its own text element.
    "Anusha_Python_Developer (1).pdf": ["Mokashi", r"re:\b0310\b"],
    "Arpit_Agrahari - Software Developer.pdf": ["Agrahari"],
    "Chirag Korat +5 years Sr. Web Developer (1).pdf": ["Korat"],
    "Chirag Vataliya.pdf": ["Vataliya"],
    "Deepak-Nagar_Resume (2).pdf": ["Nagar", "Dhakad"],
    "Deepp Sen.pdf": ["Sen"],
    "Derrick_Karanja - Software Developer.pdf": ["Kariuki", "Karanja"],
    "dinesh_updated_resume.pdf": ["Sharma"],
    "Eddah Githuku - Software Developer.pdf": ["Githuku"],
    "Gopika_Aravind_Resume (1).pdf": ["Aravind"],
    "Harish_Python Developer.pdf": ["Goud"],
    "Ishan_Attri_ATS_Resume_Final (1).pdf": ["Attri"],
    "Jatin_Kushwaha_Resume .pdf": ["Kushwaha"],
    "Kethepally_Aravind_Python_Developer_Resume (1).pdf": ["Kethepally"],
    "Komal Kanani.pdf": ["Kanani"],
    "Kunal Rathod Full Stack Developer (1).pdf": ["Rathod"],
    "Megha_FullStack+ AI (1).docx": ["Soni"],
    "Megha_Soni_FullStack+ AI (1).pdf": ["Soni"],
    "Milan-Resume-NodeJS.pdf": ["Vaghasiya"],
    "Mithilesh_Patil_CV_Senior_Backend_Engineer_new_updated (1).pdf": ["Chandrabhan", "Patil"],
    "Nilesh Python Fullstack + AI_ML Dev (1).pdf": ["Patidar"],
    "Niraj_Software_Backend (1).pdf": ["Kumar"],  # scanned, handled via OCR
    "Nisha_Gupta_Resume (2).pdf": ["Gupta"],
    "Prity_Resume.pdf": ["Kumari", "Rawat"],
    "Priyanka_Python_Resume (1).docx": ["Mhaske"],
    "Rafi-Ahmed-Software-Engineer.pdf (2).pdf": ["Ahmed"],
    "Resume - Harsh Gupta  6.8 Years (1).pdf": ["Gupta"],
    "Resume_MayurUbale_QM (1).pdf": ["Ubale"],
    "Resume_MayurUbale_QM.pdf": ["Ubale"],
    "Rumaisa - Python Developer.pdf": ["Rehan"],
    "Sachin_Shivade_Resume (1).pdf": ["Ramdas", "Shivade"],
    "Sakthi Resume (1).pdf": [r"re:(?<=SAKTHIKUMAR\s)S(?![A-Za-z])"],
    "Sanket Jethava (1).pdf": ["Jethava"],
    "Satyaranjan Swain (2).pdf": ["Swain"],
    "Shah_Shlesha_resume (1).pdf": ["Shah"],
    "Shayan Roychoudhury GenAI.PDF": ["Roychoudhury"],
    "ShehbazShaikhResume - Python .pdf": ["Shaikh"],
    "Shubham_Patware_Python_AIML_CV hurix (1).pdf": ["Patware"],
    "Siddharth_Resume - Software Developer.pdf": ["Balwant"],
    "Vara Rahul Rajana - Software Developer.pdf": ["Vara", "Rajana"],
    "Yash_Kothiya_6y (1).pdf": ["Kothiya"],
    "YUVRAJ MUSALE.pdf": ["Musale"],
    "Yugvin Python.pdf": ["Kumar"],
    # --- batch 2 ---
    "AbheyDadwal-AI - Abhey Dadwal.pdf": ["Dadwal"],
    "Abhijeet_Rojatkar_Resume - Abhijeet R.pdf": ["Rojatkar"],
    "Akash Raut - Python Developer.pdf": ["Raut"],
    "Akintola - Python Developer.pdf": ["Akintola"],
    "AkshatShahCV_2026 - Akshat Shah.pdf": ["Shah"],
    "Amit Panchal - Python Developer.pdf": ["Panchal"],
    "Anirudh_Jaju - Anirudh Jaju.pdf": ["Jaju"],
    "Arvind_Kumar_Resume_2026L.pdf": ["Kumar", "Kuntal"],
    "Aslam_Miya_Resume - Aslam Miya.pdf": ["Miya"],
    "Benedict Oshomah - Python Developer.pdf": ["Oshomah", "Emoe-Kabu", "Emoe", "Kabu"],
    "CV_Bhushan_More.pdf": [
        r"re:(?<=BHUSHAN\s)More(?![A-Za-z])"
    ],  # 'More' is a common word: only after the first name
    "Collins Onyemaobi - Pthon Developer.pdf": ["Tochukwu", "Onyemaobi"],
    "DanishrajaRes - Danish Haqqani.pdf": ["Raja", "Haqqani", "Daniishraza"],
    "David Olukolatimi - API Developer.pdf": ["Olukolatimi"],
    "Derrick_Karanja_Resume.pdf": ["Kariuki", "Karanja"],
    "DhaleMukesh3YOE.pdf.pdf": ["Dhale"],
    "Emmanuel Ayomide AI Evaluator CV.pdf": ["Ayomide", "Oluwatayo"],
    "Er.robin_singh.pdf": ["Singh"],
    "Fahad Shahzad Resume (1).pdf": ["Shahzad"],
    "GANESH CHAVAN RESUME v1 - Ganesh Chavan.docx - Google Docs.pdf": ["Chavan"],
    "Hafiz Abdullah - Software Developer.pdf": ["Abdullah"],
    "Hamza - Software Developer.pdf": ["Kaya"],
    "Harsh-Shah-FullStack.pdf": ["Shah"],
    "Harsh_Varshney_Java_SpringBoot_Microservices_4.5_Years.pdf": ["Varshney"],
    "Haya Lawansah.pdf": ["Lawansah"],
    "Hector Hugo Naranjo - Sofware Developer.pdf": ["Naranjo"],
    "Jatin_Kushwaha_Resume (5) (1).pdf": ["Kushwaha"],
    "Kenchukwu Ofodile - Python Developer.pdf": ["Ofodile"],
    "Kushal_resume_SE_Latest-1-1.pdf": ["Shah"],
    "LOKESH_AI_ENGINEER_CV - Lokesh Ippili.pdf": ["Ippili"],
    "Lucas Batista - Resume.pdf": ["Daniel", "Batista"],
    "Mamdouh AlaaEldin - Data Scientist.pdf": ["AlaaEldin", "Alaa"],
    "Manish B - Python Developer.pdf": ["Bhagchandani"],
    "Mohamed El-hadi - Software Developer.pdf": ["El-hadi", "Elhadi"],
    "MrunaliDalal_BackendDeveloper-1.pdf": ["Dalal"],
    "MrunaliDalal_BackendDeveloper.pdf": ["Dalal"],
    "Muhammad Noman (1).pdf": [
        "Qureshi",
        r"re:(?<=Muhammad\s)Noman(?![A-Za-z])",
        r"re:(?<=M\.\s)Noman(?![A-Za-z])",
    ],  # 'Noman' is his family name, keep the 'Muhammad'
    "Muhammad_Siddique_Umer_DevOps_and_Cloud_Engineer_Resume.pdf": ["Siddique", "Umer"],
    "Naukri_AkashKumarA[3y_0m].pdf": [
        "Kumar",
        r"re:(?<=KUMAR\s)A(?![A-Za-z])",
    ],  # trailing initial
    "Naukri_AkashSharma[3y_0m].pdf": ["Sharma"],
    "Naukri_AmanVyas[4y_4m].pdf": ["Vyas"],
    "Naukri_AnkurJain[6y_0m].pdf": ["Jain"],
    "Naukri_AtharvaVinayakKodre[3y_8m].pdf": ["Vinayak", "Kodre"],
    "Naukri_ChandanKumar[5y_2m].pdf": ["Kumar"],
    "Naukri_GopalPaghdar[6y_0m].pdf": ["Paghdar"],
    "Naukri_JAYMINPATEL[6y_7m].pdf": ["Patel"],
    "Naukri_KishanVaghani[6y_6m].pdf": ["Vaghani"],
    "Naukri_MangiLal[4y_1m].pdf": ["Lal", "Bishnoi"],
    "Naukri_Mr.AKULASAIKRISHNA[4y_0m]-1.pdf": ["Akula"],  # Akula is the family name
    "Naukri_Mr.AKULASAIKRISHNA[4y_0m].pdf": ["Akula"],
    "Naukri_ROHITSINGHImmediateJoiner...[10y_0m].pdf": ["Singh"],
    "Naukri_SagarPatoliya[5y_0m]-1.pdf": ["Patoliya"],
    "Naukri_SagarPatoliya[5y_0m]-2.pdf": ["Patoliya"],
    "Naukri_SagarPatoliya[5y_0m].pdf": ["Patoliya"],
    "Naukri_VishakhaKumari[3y_6m].pdf": ["Kumari", "Sinha"],
    "Neelesh_Meena - Resume (3).pdf": ["Meena"],
    "Nisha_Gupta_Resume - Nisha-Gupta.pdf": ["Gupta"],
    "Nisham_Software_Engineer_Java_backend_AI.pdf": ["Abdulkarim"],
    "Nishant_Mishra_Software_Developer_Resume.pdf": ["Mishra"],
    "NitishResume1.pdf": ["Songara"],
    "Oduyebo oluwatobi victor resume - Oluwatobi Oduyebo.pdf": ["Oduyebo", "Victor"],
    "Osaze Omonjahio - Data Scientist.pdf": ["Omonjahio"],
    "Pallavi_Bhasme_Java_Backend_Resume.pdf": ["Bhasme"],
    "Pavitra_Bhatt_Resume.pdf": ["Bhatt"],
    "Piyush Suneja Resume - Piyush Suneja.pdf": ["Suneja"],
    "Pradeep_Dubey_Resume.pdf": ["Dubey"],
    "Prashant_Mishra_Resume.pdf": ["Mishra"],
    "Rahman Oloritun - Python Developer.pdf": ["Oloritun"],
    "Rahul_Mete_Java_Developer_Resume.pdf": ["Mete"],
    "Rahul_Mogal.pdf": ["Vijay", "Mogal"],
    "Ramesh_Java_Backend_Developer_10Years.pdf": ["Yelagala"],  # Yelagala is the family name
    "Ravi Bhushan Chauhan - Python Developer.pdf": ["Bhushan", "Chauhan"],
    "Resume (1).pdf": ["Kumar", r"re:\bDK\b"],  # DK: initials in the header block
    "Rishabh M 6+ Full Stack Engineer.pdf": ["Mandal"],
    "Rithika Reddy.pdf": ["Reddy"],
    "Rutul_Patel_23_08.pdf": ["Patel"],
    "SKGanguly_CV_Gen-AI - Soumya Kanti Ganguly.pdf": ["Kanti", "Ganguly"],
    "Sahed Abdelziz - Python Developer.pdf": ["Mohamed", "Abdelziz"],
    "Sakshi Patil DA.pdf": ["Patil"],
    "SandeepSidhwaniResume - Sandeep Sidhwani.pdf": ["Sidhwani"],
    "Sathishkumar_A.pdf": ["Arumugam", r"re:(?<=SATHISHKUMAR\s)A(?![A-Za-z])"],  # bare initial
    "Satyam Mishra Resume.pdf": ["Mishra"],
    "Satyam_Jain_Resume - Satyam Jain.pdf": ["Jain"],
    "Shivansh_resume.pdf": ["Keshari"],
    "Shivkaran_Singh_Python AI ML CV.pdf": ["Singh"],
    "Shruti Agarwal_Resume_final-2 - Shruti Agarwal.pdf": ["Agarwal"],
    "Sreelesh B - Resume_NEWHEADER.pdf": [
        r"re:(?<=SREELESH\s)B(?![A-Za-z])"
    ],  # single-letter surname
    "Suhas_Khot_Data_Analyst_PowerBI.pdf": ["Khot"],
    "Sushil Prasad Shaw - Python Developer.pdf": ["Prasad", "Shaw"],
    "Syed Hashmi - Python Developer.pdf": ["Kamran", "Hashmi"],
    "TANISHQ RAJ - Tanishq Raj.pdf": ["Raj"],
    "Tushar_Jaiwal.pdf": ["Jaiwal"],
    "Vaibhav_Kandharkar_Resume_2026.pdf": ["Kandharkar"],
    "Vansh_dhiman_backenddeveloper (1).pdf": ["Dhiman"],
    "Vasu_Resume (1).pdf": [
        "Upadhyay",
        r"re:\bvasuupadhyay\w*",
    ],  # profile slug, surname glued to first name
    "arthavn_resume (1) - Arthav.pdf": ["Jain"],
    "aswin_resume - Aswin S.pdf": ["Thampalakad", r"re:(?<=Aswin\s)\.S\."],  # middle initial
    "edit.pdf": [],  # surname appears only inside the email
    "jaspreetSingh_CV_helvet.pdf": ["Singh"],
    "raj kumar.pdf": ["Kumar"],
    "resume (2) (1).pdf": ["Kumar"],
    "rishikesh-kourav (2).pdf": ["Kourav"],
    "shittu wahab.pdf": ["Wahab"],
    "software_developer_Sujal.pdf": ["Kumar", "Gupta"],
}

# Output filename per source file (surname stripped).
OUT_NAME: dict[str, str] = {
    "Aakash_PythonDeveloper (1).pdf": "Aakash_Python_Developer.pdf",
    "Aman_Chaudhary_Resume.pdf": "Aman_Backend_Engineer.pdf",
    "Aman_Resume.docx": "Aman_Backend_Engineer.docx",
    "Amar (1).pdf": "Amar_Software_Engineer.pdf",
    "Amit_Kumar_Resume_PDF_Format-1 (1).pdf": "Amit_Python_Fullstack_Developer.pdf",
    "Amol Kale.pdf": "Amol_Python_Developer.pdf",
    "Anusha_Python_Developer (1).pdf": "Anusha_Python_Developer.pdf",
    "Arpit_Agrahari - Software Developer.pdf": "Arpit_Software_Developer.pdf",
    "Chirag Korat +5 years Sr. Web Developer (1).pdf": "Chirag_Sr_Web_Developer.pdf",
    "Chirag Vataliya.pdf": "Chirag_Python_Developer.pdf",
    "Deepak-Nagar_Resume (2).pdf": "Deepak_Backend_Engineer.pdf",
    "Deepp Sen.pdf": "Deep_Full_Stack_AI_Engineer.pdf",
    "Derrick_Karanja - Software Developer.pdf": "Derrick_Software_Developer.pdf",
    "dinesh_updated_resume.pdf": "Dinesh_Python_LLM_Engineer.pdf",
    "Eddah Githuku - Software Developer.pdf": "Eddah_Software_Developer.pdf",
    "Gopika_Aravind_Resume (1).pdf": "Gopika_AI_Engineer.pdf",
    "Harish_Python Developer.pdf": "Harish_Python_Developer.pdf",
    "Ishan_Attri_ATS_Resume_Final (1).pdf": "Ishan_Data_Scientist.pdf",
    "Jatin_Kushwaha_Resume .pdf": "Jatin_Backend_Developer.pdf",
    "Kethepally_Aravind_Python_Developer_Resume (1).pdf": "Aravind_Python_Developer.pdf",
    "Komal Kanani.pdf": "Komal_Senior_Python_Architect.pdf",
    "Kunal Rathod Full Stack Developer (1).pdf": "Kunal_Full_Stack_Developer.pdf",
    "Megha_FullStack+ AI (1).docx": "Megha_FullStack_AI.docx",
    "Megha_Soni_FullStack+ AI (1).pdf": "Megha_FullStack_AI.pdf",
    "Milan-Resume-NodeJS.pdf": "Milan_NodeJS_Developer.pdf",
    "Mithilesh_Patil_CV_Senior_Backend_Engineer_new_updated (1).pdf": "Mithilesh_Senior_Backend_Engineer.pdf",
    "Nilesh Python Fullstack + AI_ML Dev (1).pdf": "Nilesh_Python_Fullstack_AI_ML.pdf",
    "Niraj_Software_Backend (1).pdf": "Niraj_Backend_Engineer.pdf",
    "Nisha_Gupta_Resume (2).pdf": "Nisha_Full_Stack_Developer.pdf",
    "Prity_Resume.pdf": "Prity_Python_Developer.pdf",
    "Priyanka_Python_Resume (1).docx": "Priyanka_Python_Developer.docx",
    "Rafi-Ahmed-Software-Engineer.pdf (2).pdf": "Rafi_Software_Engineer.pdf",
    "Resume - Harsh Gupta  6.8 Years (1).pdf": "Harsh_Python_Developer.pdf",
    "Resume_MayurUbale_QM (1).pdf": "Mayur_QA_Manager.pdf",
    "Resume_MayurUbale_QM.pdf": "Mayur_QA_Manager_copy.pdf",
    "Rumaisa - Python Developer.pdf": "Rumaisa_Python_Developer.pdf",
    "Sachin_Shivade_Resume (1).pdf": "Sachin_Software_Developer.pdf",
    "Sakthi Resume (1).pdf": "Sakthikumar_Resume.pdf",
    "Sanket Jethava (1).pdf": "Sanket_Tech_Lead.pdf",
    "Satyaranjan Swain (2).pdf": "Satyaranjan_Fullstack_Engineer.pdf",
    "Shah_Shlesha_resume (1).pdf": "Shlesha_Full_Stack_Developer.pdf",
    "Shayan Roychoudhury GenAI.PDF": "Shayan_GenAI_Data_Scientist.pdf",
    "ShehbazShaikhResume - Python .pdf": "Shehbaz_Python_Developer.pdf",
    "Shubham_Patware_Python_AIML_CV hurix (1).pdf": "Shubham_Python_AIML_Developer.pdf",
    "Siddharth_Resume - Software Developer.pdf": "Siddharth_Software_Developer.pdf",
    "Vara Rahul Rajana - Software Developer.pdf": "Rahul_Software_Developer.pdf",
    "Yash_Kothiya_6y (1).pdf": "Yash_Full_Stack_Developer.pdf",
    "YUVRAJ MUSALE.pdf": "Yuvraj_Full_Stack_Developer.pdf",
    "Yugvin Python.pdf": "Yugvin_Software_Engineer.pdf",
    # --- batch 2 ---
    "AbheyDadwal-AI - Abhey Dadwal.pdf": "Abhey_AI_ML_Developer.pdf",
    "Abhijeet_Rojatkar_Resume - Abhijeet R.pdf": "Abhijeet_Software_Engineer.pdf",
    "Akash Raut - Python Developer.pdf": "Akash_Senior_Software_Engineer.pdf",
    "Akintola - Python Developer.pdf": "Kunle_Full_Stack_Engineer.pdf",
    "AkshatShahCV_2026 - Akshat Shah.pdf": "Akshat_Senior_Backend_Engineer.pdf",
    "Amit Panchal - Python Developer.pdf": "Amit_Data_Analyst.pdf",
    "Anirudh_Jaju - Anirudh Jaju.pdf": "Anirudh_ML_Engineer.pdf",
    "Arvind_Kumar_Resume_2026L.pdf": "Arvind_Java_Backend_Engineer.pdf",
    "Aslam_Miya_Resume - Aslam Miya.pdf": "Aslam_AI_Engineer.pdf",
    "Benedict Oshomah - Python Developer.pdf": "Benedict_Python_Developer.pdf",
    "CV_Bhushan_More.pdf": "Bhushan_Java_Full_Stack_Developer.pdf",
    "Collins Onyemaobi - Pthon Developer.pdf": "Collins_AI_Backend_Engineer.pdf",
    "DanishrajaRes - Danish Haqqani.pdf": "Danish_Technology_Professional.pdf",
    "David Olukolatimi - API Developer.pdf": "David_AI_Automation_Engineer.pdf",
    "Derrick_Karanja_Resume.pdf": "Derrick_Full_Stack_Engineer.pdf",
    "DhaleMukesh3YOE.pdf.pdf": "Mukesh_Java_Backend_Developer.pdf",
    "Emmanuel Ayomide AI Evaluator CV.pdf": "Emmanuel_AI_Evaluator.pdf",
    "Er.robin_singh.pdf": "Robin_Full_Stack_Engineer.pdf",
    "Fahad Shahzad Resume (1).pdf": "Fahad_Senior_Full_Stack_AI_Engineer.pdf",
    "GANESH CHAVAN RESUME v1 - Ganesh Chavan.docx - Google Docs.pdf": "Ganesh_Software_Developer.pdf",
    "Hafiz Abdullah - Software Developer.pdf": "Hafiz_Software_Engineer.pdf",
    "Hamza - Software Developer.pdf": "Hamza_Backend_Developer.pdf",
    "Harsh-Shah-FullStack.pdf": "Harsh_Full_Stack_Developer.pdf",
    "Harsh_Varshney_Java_SpringBoot_Microservices_4.5_Years.pdf": "Harsh_Java_Backend_Developer.pdf",
    "Haya Lawansah.pdf": "Haya_Software_Engineer.pdf",
    "Hector Hugo Naranjo - Sofware Developer.pdf": "Hector_Software_Developer.pdf",
    "Jatin_Kushwaha_Resume (5) (1).pdf": "Jatin_NodeJS_Backend_Developer.pdf",
    "Kenchukwu Ofodile - Python Developer.pdf": "Kenechukwu_Senior_Python_Developer.pdf",
    "Kushal_resume_SE_Latest-1-1.pdf": "Kushal_Software_Engineer.pdf",
    "LOKESH_AI_ENGINEER_CV - Lokesh Ippili.pdf": "Lokesh_AI_Engineer.pdf",
    "Lucas Batista - Resume.pdf": "Lucas_Backend_Software_Engineer.pdf",
    "Mamdouh AlaaEldin - Data Scientist.pdf": "Mamdouh_Data_Scientist.pdf",
    "Manish B - Python Developer.pdf": "Manish_Lead_Data_Scientist.pdf",
    "Mohamed El-hadi - Software Developer.pdf": "Mohamed_Software_Engineer.pdf",
    "MrunaliDalal_BackendDeveloper-1.pdf": "Mrunali_Java_Backend_Developer.pdf",
    "MrunaliDalal_BackendDeveloper.pdf": "Mrunali_Java_Backend_Developer_copy.pdf",
    "Muhammad Noman (1).pdf": "Muhammad_Graphic_Designer.pdf",
    "Muhammad_Siddique_Umer_DevOps_and_Cloud_Engineer_Resume.pdf": "Muhammad_DevOps_Cloud_Engineer.pdf",
    "Naukri_AkashKumarA[3y_0m].pdf": "Akash_Python_Full_Stack_Developer.pdf",
    "Naukri_AkashSharma[3y_0m].pdf": "Akash_Backend_Data_Engineer.pdf",
    "Naukri_AmanVyas[4y_4m].pdf": "Aman_Product_Engineer.pdf",
    "Naukri_AnkurJain[6y_0m].pdf": "Ankur_Python_Backend_Developer.pdf",
    "Naukri_AtharvaVinayakKodre[3y_8m].pdf": "Atharva_Data_Engineer.pdf",
    "Naukri_ChandanKumar[5y_2m].pdf": "Chandan_Senior_Data_Analyst.pdf",
    "Naukri_GopalPaghdar[6y_0m].pdf": "Gopal_Senior_Full_Stack_Engineer.pdf",
    "Naukri_JAYMINPATEL[6y_7m].pdf": "Jaymin_Full_Stack_Developer.pdf",
    "Naukri_KishanVaghani[6y_6m].pdf": "Kishan_Senior_Software_Engineer.pdf",
    "Naukri_MangiLal[4y_1m].pdf": "Mangi_Software_Engineer.pdf",
    "Naukri_Mr.AKULASAIKRISHNA[4y_0m]-1.pdf": "Sai_Krishna_Software_Engineer.pdf",
    "Naukri_Mr.AKULASAIKRISHNA[4y_0m].pdf": "Sai_Krishna_Software_Engineer_copy.pdf",
    "Naukri_ROHITSINGHImmediateJoiner...[10y_0m].pdf": "Rohit_QA_Lead.pdf",
    "Naukri_SagarPatoliya[5y_0m]-1.pdf": "Sagar_Full_Stack_Engineer_copy1.pdf",
    "Naukri_SagarPatoliya[5y_0m]-2.pdf": "Sagar_Full_Stack_Engineer_copy2.pdf",
    "Naukri_SagarPatoliya[5y_0m].pdf": "Sagar_Full_Stack_Engineer.pdf",
    "Naukri_VishakhaKumari[3y_6m].pdf": "Vishakha_Software_Engineer.pdf",
    "Neelesh_Meena - Resume (3).pdf": "Neelesh_Tech_Lead.pdf",
    "Nisha_Gupta_Resume - Nisha-Gupta.pdf": "Nisha_Python_React_Developer.pdf",
    "Nisham_Software_Engineer_Java_backend_AI.pdf": "Nisham_Senior_Java_Backend_Engineer.pdf",
    "Nishant_Mishra_Software_Developer_Resume.pdf": "Nishant_Software_Developer.pdf",
    "NitishResume1.pdf": "Nitish_AI_Training_Software_Engineer.pdf",
    "Oduyebo oluwatobi victor resume - Oluwatobi Oduyebo.pdf": "Oluwatobi_Senior_AI_ML_Engineer.pdf",
    "Osaze Omonjahio - Data Scientist.pdf": "Osaze_Systems_Technology_Officer.pdf",
    "Pallavi_Bhasme_Java_Backend_Resume.pdf": "Pallavi_Java_Backend_Developer.pdf",
    "Pavitra_Bhatt_Resume.pdf": "Pavitra_Software_Developer.pdf",
    "Piyush Suneja Resume - Piyush Suneja.pdf": "Piyush_Full_Stack_Developer.pdf",
    "Pradeep_Dubey_Resume.pdf": "Pradeep_AI_Engineer.pdf",
    "Prashant_Mishra_Resume.pdf": "Prashant_Senior_SDET.pdf",
    "Rahman Oloritun - Python Developer.pdf": "Rahman_Python_Developer.pdf",
    "Rahul_Mete_Java_Developer_Resume.pdf": "Rahul_Java_Developer.pdf",
    "Rahul_Mogal.pdf": "Rahul_Informatica_ETL_Developer.pdf",
    "Ramesh_Java_Backend_Developer_10Years.pdf": "Ramesh_Senior_Software_Developer.pdf",
    "Ravi Bhushan Chauhan - Python Developer.pdf": "Ravi_Senior_Python_Engineer.pdf",
    "Resume (1).pdf": "Deepak_Golang_Backend_Engineer.pdf",
    "Rishabh M 6+ Full Stack Engineer.pdf": "Rishabh_Full_Stack_Developer.pdf",
    "Rithika Reddy.pdf": "Rithika_Site_Reliability_Engineer.pdf",
    "Rutul_Patel_23_08.pdf": "Rutul_Data_Scientist.pdf",
    "SKGanguly_CV_Gen-AI - Soumya Kanti Ganguly.pdf": "Soumya_GenAI_Developer.pdf",
    "Sahed Abdelziz - Python Developer.pdf": "Saher_AI_Engineer.pdf",
    "Sakshi Patil DA.pdf": "Sakshi_Data_Analyst.pdf",
    "SandeepSidhwaniResume - Sandeep Sidhwani.pdf": "Sandeep_Full_Stack_Developer.pdf",
    "Sathishkumar_A.pdf": "Sathishkumar_C_Cpp_Engineer.pdf",
    "Satyam Mishra Resume.pdf": "Satyam_Full_Stack_Developer.pdf",
    "Satyam_Jain_Resume - Satyam Jain.pdf": "Satyam_GenAI_Developer.pdf",
    "Shivansh_resume.pdf": "Shivansh_Senior_Data_Engineer.pdf",
    "Shivkaran_Singh_Python AI ML CV.pdf": "Shivkaran_Python_AI_ML_Developer.pdf",
    "Shruti Agarwal_Resume_final-2 - Shruti Agarwal.pdf": "Shruti_Software_Engineer.pdf",
    "Sreelesh B - Resume_NEWHEADER.pdf": "Sreelesh_Data_Engineer.pdf",
    "Suhas_Khot_Data_Analyst_PowerBI.pdf": "Suhas_Data_Analyst.pdf",
    "Sushil Prasad Shaw - Python Developer.pdf": "Sushil_Senior_AI_Engineer.pdf",
    "Syed Hashmi - Python Developer.pdf": "Syed_Data_Engineer.pdf",
    "TANISHQ RAJ - Tanishq Raj.pdf": "Tanishq_AI_Data_Science.pdf",
    "Tushar_Jaiwal.pdf": "Tushar_Senior_Java_Engineer.pdf",
    "Vaibhav_Kandharkar_Resume_2026.pdf": "Vaibhav_Full_Stack_Java_Developer.pdf",
    "Vansh_dhiman_backenddeveloper (1).pdf": "Vansh_Backend_Developer.pdf",
    "Vasu_Resume (1).pdf": "Vasu_Network_Engineer.pdf",
    "arthavn_resume (1) - Arthav.pdf": "Arthav_Software_Engineer.pdf",
    "aswin_resume - Aswin S.pdf": "Aswin_Full_Stack_Software_Engineer.pdf",
    "edit.pdf": "Vinay_Senior_DevOps_Engineer.pdf",
    "jaspreetSingh_CV_helvet.pdf": "Jaspreet_Backend_Platform_Engineer.pdf",
    "raj kumar.pdf": "Raj_Senior_DevOps_Engineer.pdf",
    "resume (2) (1).pdf": "Kishan_Senior_AI_ML_Engineer.pdf",
    "rishikesh-kourav (2).pdf": "Rishikesh_DevOps_Engineer.pdf",
    "shittu wahab.pdf": "Shittu_AI_Training_Specialist.pdf",
    "software_developer_Sujal.pdf": "Sujal_Software_Developer.pdf",
}

# Files where the first name is glued to the surname in one word: put the first
# name back after redacting the whole word. {source file: first name}
REINSERT: dict[str, str] = {
    "Rafi-Ahmed-Software-Engineer.pdf (2).pdf": "Rafi",
}

# Headshot image xrefs to strip (a face identifies the candidate).
PHOTOS: dict[str, list[int]] = {
    # --- batch 2 ---
    "LOKESH_AI_ENGINEER_CV - Lokesh Ippili.pdf": [15],
    "Manish B - Python Developer.pdf": [25],
    "SandeepSidhwaniResume - Sandeep Sidhwani.pdf": [36],
    "Syed Hashmi - Python Developer.pdf": [7],
    # 38 headshot; 142 Fiverr profile card (face + seller name); 144 a contact
    # card with the phone number and email baked into the pixels.
    "Muhammad Noman (1).pdf": [38, 142, 144],
    "Resume_MayurUbale_QM (1).pdf": [6],
    "Resume_MayurUbale_QM.pdf": [6],
    "Milan-Resume-NodeJS.pdf": [12],
    "Sanket Jethava (1).pdf": [460],
}
